### ISSUE TITLE
Undefined index: HTTP_HOST in /config/multisites_config.php

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Multisites#26]
When executing via CLI:

```
php app/console
```

The following notice is output:

```
PHP Notice:  Undefined index: HTTP_HOST in /config/multisites_config.php on line 3
```

The ZikulaKernel includes the file multisites_config.php, if it is readable.

**Comment by Guite** [comment]
Fixed by 9d2e66e72a17757b36c26c6889c700d88868b345
