### ISSUE TITLE
Warning: Multisites has an invalid composer.json file which could not be decoded.

### ISSUE THREAD

**Issue by shefik** [zikula-modules/Multisites#81]
The latest build of the Multisites modules throws this error at `/extensions/module/list`, even though the module is not attempting to install.

```Warning: Multisites has an invalid composer.json file which could not be decoded.```

**Comment by Guite** [comment]
Which branch are you referring to?

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/Multisites/commit/cf0f329e75614a7a72c5dd0904e034c322657114
